### ISSUE TITLE
Clarify how to use use OPTIONS and HEAD to convey information about which profiles are available

### ISSUE THREAD

**Issue by larsgsvensson** [ProfileNegotiation/I-D-Accept--Schema#26]
On [public-dxwg-comments, Kam Hay Fung commented](https://lists.w3.org/Archives/Public/public-dxwg-comments/2018Aug/0002.html) that the use of only http status codes might not be enough to let a client know which profiles are available and suggests the use of the http methods OPTIONS and HEAD. This sounds very reasonable and we should also perhaps look at the http `300 Multiple Choices`. In the DXWG there is also a discussion on the use of URL query parameters to specify profiles but that should not be part of the I-D.

**Comment by RubenVerborgh** [comment]
I was surprised to see

> The Proposal relies on HTTP error codes (e.g. 406, 500) in the negotiation process to let user agents determine the right profile to use.

and, in the proposal,

> > If in such a case the server does not implement profile negotiation, the server is
more likely to return a 500 (Internal server error) response instead of 406.

which is not a good idea and conflicts with #25.

We should definitely not use status codes for that.
